version: '3'

services:
  zookeeper:
    image: zookeeper
    restart: always
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka
    restart: always
    ports:
      - "9092:9092"
    links:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: ${HOST_IP}:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${HOST_IP}:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    env_file:
      - .env
